version: '3'
services:
  prod:
    image: "simponic/simponicxyz"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - 'db'
  db:
    image: 'postgres:14'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
