#+TITLE: simponic

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/css/style.css" />
#+HTML_HEAD_EXTRA: <meta name="viewport" content="width=device-width, initial-scale=1">

#+OPTIONS: inlineimages toc:nil
#+STARTUP: fold


[[./img/logo.svg]]

#+BEGIN_EXPORT html
<?php
  $motds = [
     "hello, world!",
     "emacs > vim",
     "functional programming on top",
     "\"a baller, a shot caller, an arch linux installer\"",
     "one distro to rule them all, and in the darkness bind them",
     "proprietary software leads to anger, anger leads to hate, hate leads to suffering",
     "i'll tell you once, and i'll tell you again. there's always a prime between n and 2n.",
     "1. e4 e5 2. ke2",
     ">++++++[<+++++++++>-]<.+++.-----.--.--.",
     "it's certainly the year of the linux desktop",
     "dwm is a sweet window manager",
     "e^(iπ)+1 is cool!",
     "lambda calculus isn't calculus!",
     "also try minecraft!",
     "the days are just packed",
     "when will we have no-instruction-set-computing?",
     "i'm r u r' u' and i know it"
  ];
  echo "<h3 style='text-align:center'>motd: <em>" . $motds[array_rand($motds)] . "</em></h3>";
?>
#+END_EXPORT


* huh?
yes, i stole [[http://bettermotherfuckingwebsite.com][that other guy's css]].

my name is elizabeth, or lizzy / liz. i'm 19, president
of the [[https://linux.usu.edu][USU FSLC]], student in computer science, and intern at AWS...
also a filthy liberal :)

sometimes, i make (what i believe to be) cool stuff. like [[https://chessh.linux.usu.edu][cheSSH]]!

** regulars be saddened, for we are no longer elixir
i used to have a kinda cool site i built a few years back, to explore [[https://www.phoenixframework.org/][phoenix]].
but i never ended up using the features i spent so
long making - a time card clock & exporter for contract use, contact form w/
captcha, dynamic blog system with comments and roles, etc. it was my first
full-stack app i made for fun, at the time; so pulling the plug was a little
bittersweet.

all you'll get here now, mostly, is black text and some of my takes.
whether they're good or bad is up to you, dear reader.

* links, contact
+ [[https://github.com/Simponic][my github]]
+ [[https://www.linkedin.com/in/elizabeth-hunt-031932229/][linkedin]]
+ [[mailto:elizabeth.hunt@simponic.xyz][elizabeth.hunt@simponic.xyz]]
+ [[https://github.com/usufslc][usufslc github]]
* monies
i believe salaries should be public & discussable information. to least "help"
combat corporate greed (though, we should all be being paid the same... ideally)

| age     | position                             | start    | end                                     | monies                                          | would work again?                                                                                     |
|---------+--------------------------------------+----------+-----------------------------------------+-------------------------------------------------+-------------------------------------------------------------------------------------------------------|
| 19 - 19 | sde intern @ aws                     | may 2023 | jul 2023                                | $9180/month + ~$7k housing stipend for 12 weeks | can't really say yet.                                                                                 |
| 19 - 19 | student networking sde               | sep 2022 | may 2023 (coming back after summer '23) | $18 / hour                                      | yes. money is not great and i am underpaid. but i get to work on cool stuff with cool people :), and it's the pay cap for student positions |
| 18 - 18 | sde intern @ aws                     | may 2022 | aug 2022                                | $9180/month + ~$6k housing stipend for 12 weeks | yes; i did                                                                                            |
| 17 - 18 | contractor developer @ maiden voyage | apr 2021 | nov 2021                                | $13 / hour                                      | no, i was SEVERELY underpaid (and bored), for the stuff i was doing, in hindsight.                    |

* things i like...
+ elixir, lisp, c, (some aspects of) javascript. i don't really know how to feel about java, but i've used it the most out of anything.
+ math - algebra of abstract or linear variety, number theory, analysis, discrete. you name it. shove it in my brain already.
+ functional paradigms.
+ emacs.
+ linux.
+ chess.
+ minecraft.
+ democratic nations that practice social ideals to better the lives of their citizens rather than capital owners.
* things i'm not so much a fan of...
+ c++ - when it's being cringe. which is unfortunately a lot of the fucking time.
+ "microshaft wangblows" - the phattest of sumos.
+ over-abstracted oop.
+ snap.
+ religion. but, like, only if it's mixed in with nationalism/conservatism. i have no qualms with religion or
  people practicing in general, i just have some beef with mormons; mainly due to growing up very lds, in a small,
  lds community.
+ just money in general lmao. not the biggest fan of markets i must say.
  there might not be a good alternative currently, which is why UBI is a good compromise of both worlds.
